### ISSUE TITLE
error in the wild: Found a later subchain with eldest kid 

### ISSUE THREAD

**Issue by maxtaco** [keybase/libkeybase-js#11]
See keybase/keybase-issues#1769

**Comment by oconnor663** [comment]
The server needs to enforce that we don't reuse eldest keys. (Bit of a hack, but it'll matter less when most eldest keys are device keys.)

**Comment by oconnor663** [comment]
Server-side fix: https://github.com/keybase/keybase/pull/478

**Comment by oconnor663** [comment]
As part of this, we need to update the node client to go down the `is_update` codepath on `key/add.json`.

**Comment by oconnor663** [comment]
I was wrong, no client change is needed. This is done. (Just confirmed by creating an account with the node client, making a few sigs, running `keybase revoke` to nuke everything, and then trying to `keybase push` the same eldest key again.)
