### ISSUE TITLE
Allow caching of signature verifications

### ISSUE THREAD

**Issue by maxtaco** [keybase/libkeybase-js#2]
Current plan is to pass in a list of sigs previously verified.

**Comment by maxtaco** [comment]
Also need test cases for this.

**Comment by oconnor663** [comment]
Done, and tested in libkeybase with a mock cache, but needs to be tested on the node-client side.

**Comment by oconnor663** [comment]
Ah, I suppose that's tracked in https://github.com/keybase/node-client/issues/198
